### ISSUE TITLE
Weird return using Sequel

### ISSUE THREAD

**Issue by jnylen** [jsonapi-rb/hanami#10]
Hi,
Returning data is quite weird:
```ruby
[:data, [{:id=>"1", :type=>:channel, :attributes=>{:name=>"hi", :slug=>"hi"}}]]
```

Controller:
```ruby
module ApiV2::Controllers::Channel
  class Index
    include ApiV2::Action
    include JSONAPI::Hanami::Action

    def call(params)
      self.data = Channel.all
      #self.include = [:author, comments: [:author]]
      #self.fields = { users: [:name, :email] }
      #self.status = 201
    end
  end
end
```

**Comment by beauby** [comment]
Looks like a `.to_json` is missing somewhere, thanks for pointing it out!

**Comment by beauby** [comment]
Specifically [here](https://github.com/jsonapi-rb/jsonapi-hanami/blob/master/lib/jsonapi/hanami/rendering.rb#L29).

**Comment by jnylen** [comment]
Working now.

**Comment by tragiclifestories** [comment]
For anyone else that stumbles upon this: the problem is that sometimes bundler will resolve incompatible versions of the other JSONAPI gems. The solution is to pin to `~> 0.1.3` for both `jsonapi-serializable` and `jsonapi-renderer`.
